### ISSUE TITLE
lib/repositories/vimeo_repository.dart:1:8: Error: Error when reading 'lib/environment.dart'

### ISSUE THREAD

**Issue by msterzhang** [hanniiel/flutter_tv#1]

**Comment by hanniiel** [comment]
Hi there I created this class to not post confidencial information you can solve it by creating a class and replacing the info there.
`class Environment { static const String VIMEO_TOKEN ="here_your_token"; }`
or if you use another streaming service that might work as well.
let me know if there's another inconvenient. plus if u use firebase include the .json into the project or replace that with you own implementation. I will update the wiki later. best regards
