### ISSUE TITLE
missing files from the project

### ISSUE THREAD

**Issue by NatyN-teac** [hanniiel/flutter_tv#2]
hello , i cloned your project to learn from it, but found error during building missing Environment.dart file in the project . Can you help me with that please?

**Comment by hanniiel** [comment]
> hello , i cloned your project to learn from it, but found error during building missing Environment.dart file in the project . Can you help me with that please?

Hi there, sure. you have to create a class "Enviroment" then put requested vars there.
https://github.com/hanniiel/flutter_tv/issues/1#issuecomment-727271939
