### ISSUE TITLE
Can you provide your Firestore structure for Vimeo trainings ?

### ISSUE THREAD

**Issue by purelog1c** [hanniiel/flutter_tv#4]
Hi again,

We are working on your project and we migirated it to the newer version. We also could create Category collection as we checked the entity structure in your Project. Unfortunately, we are quite stuck on how you did structure your trainings Collection on Firestore ? Could you show us some screenshots including trainings collection and data entities or drawings or anything that can help ?

**Comment by hanniiel** [comment]
![image](https://user-images.githubusercontent.com/13456748/150653001-09762ff2-6df1-4298-be3e-fe46e3122f7f.png)
![image](https://user-images.githubusercontent.com/13456748/150653013-00653145-435b-49d7-aa70-4534bdc56f08.png)
![image](https://user-images.githubusercontent.com/13456748/150653019-c5624461-e799-4dc9-90fc-05e27e8b5c5f.png)

**Comment by purelog1c** [comment]
We figured it out. Thank you for reply! Again thank you for your great work!
